version: "3.7"

services:
  # # Golang app
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   container_name: app
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - net
  #   depends_on:
  #     - database

  # Database
  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - /home/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - net

  # Database client
  adminer:
    build:
      context: .
      dockerfile: ./docker/adminer/Dockerfile
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=mvt
    networks:
      - net
    depends_on:
      - database

networks:
  net:
    driver: bridge
