version: "3.7"

services:
  # Database
  database:
    image: postgres:alpine
    restart: always
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/docker/volumes/postgres:/var/lib/postgresql/data

  # Database client
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=mvt
    depends_on:
      - database
